config/routes.rb
Rails.application.routes.draw do
  resources :services do 
  	resources :pings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'services#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ping.rb
class Ping < ApplicationRecord

	belongs_to :service

	before_save :check_service
	
	default_scope { order(created_at: :desc) }

	private
		def check_service 
			check = Net::Ping::External.new(service.host)
	    if check.ping?
	    	self.service_up = service.up!
	    else
	    	self.service_up = !service.down!
	    	ServiceMailer.send_error(service).deliver_now
	    end
		end
end

app/models/service.rb
class Service < ApplicationRecord
	include AASM
	has_many :pings, dependent: :destroy


	validates :name, presence: true
	validates :host, presence: true


	aasm do
		state :sleeping, :initial => true
    state :running

		event :up do
      transitions :from => :sleeping, :to => :running
      transitions :from => :running, :to => :running
    end

   	event :down do
     	transitions :from => :running, :to => :sleeping
      transitions :from => :sleeping, :to => :sleeping
    end
	end


	def state
		self.aasm_state
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pings_controller.rb
class PingsController < ApplicationController

	def index
		@service = Service.find(params[:service_id])
		@ping_history = @service.try(:pings).page(params[:page]).per(ENV['PER_PAGE'].to_i)
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :ip, :host)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonitoringServices</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>History</h1>

<div class="panel panel-default">
  <div class="panel-heading">History of Service <%=@service.name%></div>
  <table class='table'>
    <thead>
      <tr>
        <th>Datetime</th>
        <th>Available</th>
      </tr>
    </thead>

    <tbody>
      <% @ping_history.each do |p| %>
        <tr>
          <td><%=p.created_at%></td>
          <td>
          	<% cls = p.service_up ? 'success' : 'danger'%>
          	<span class="label label-<%=cls%>"><%=p.service_up%></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%=paginate(@ping_history)%>
<br>
<%= link_to 'Back', service_path(@service), class: 'btn btn-default' %>

app/views/services/_form.html.erb
<div class='col col-md-8'>
  <%= form_with(model: service, local: true, class: 'form-horizontal') do |form| %>
    <% if service.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

        <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-group'>
      <%=form.label :name%>
      <%=form.text_field :name, placeholder: :name, class: 'form-control'%>
    </div>
    <div class='form-group'>
      <%=form.label :ip%>
      <%=form.text_field :ip, placeholder: :ip, class: 'form-control'%>
    </div>
    <div class='form-group'>
      <%=form.label :host%>
      <%=form.text_field :host, placeholder: :host, class: 'form-control'%>
    </div>
     

    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<div class='col col-md-12'>
	<%= link_to 'Show', @service, class: 'btn btn-default' %> |
	<%= link_to 'Back', services_path, class: 'btn btn-default' %>
</div>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<div class="panel panel-default col col-md-8">
  <div class="panel-heading">List of all services</div>
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Ip</th>
        <th>Name</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%=service.name%></td>
          <td><%=service.ip%></td>
          <td><%=service.host%></td>
          <td><span><%=service.state%></span></td>
          <td>
            <%= link_to 'Show', service, class: 'btn btn-default' %>
            <%= link_to 'Edit', edit_service_path(service), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <%= link_to 'History', service_pings_path(service), class: 'btn btn-default'%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<div class='col col-md-12'>
  <%= link_to 'New Service', new_service_path, class: 'btn btn-default' %>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<div class='col col-md-12'>
	<%= link_to 'Back', services_path, class: 'btn btn-default' %>
</div>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Service</h1>
<% [:name, :ip, :host, :state].each do |attribute| %>
	<div class='col col-md-8'>
		<div class="panel panel-default">
		  <div class="panel-body">
		    <strong><%=I18n.t(:"activerecord.attributes.service.#{attribute}")%>:</strong>
		  </div>
		  <div class="panel-footer"><%= @service.send(attribute)%></div>
		</div>
	</div>

<% end %>

<div class='col col-md-12'>
	<%= link_to 'Edit', edit_service_path(@service), class: 'btn btn-primary' %> |
	<%= link_to 'Back', services_path, class: 'btn btn-default'%>
	<%= link_to 'History', service_pings_path(@service), class: 'btn btn-default'%>
</div>